package com.theactigraph.actilife.api.models;

public enum Action {
	ACTILIFE_MINIMIZE,
	ACTILIFE_RESTORE,
	WIRELESS_SCAN_START,
	WIRELESS_SCAN_STOP,
	WIRELESS_DEVICE_IDENTIFY,
	WIRELESS_DEVICE_REALTIME_START,
	WIRELESS_DEVICE_REALTIME_STOP,
	WIRELESS_DEVICE_BURST,
	USB_LIST,
	USB_DOWNLOAD,
}
