package com.theactigraph.actilife.api.models;

public enum Action {
	ACTILIFE_MINIMIZE,
	ACTILIFE_RESTORE,
	ACTILIFE_VERSION,
	API_VERSION,
	CONVERT_FILE,
	WIRELESS_SCAN_START,
	WIRELESS_SCAN_STOP,
	WIRELESS_IDENTIFY,
	WIRELESS_INITIALIZE,
	WIRELESS_REALTIME_START,
	WIRELESS_REALTIME_STOP,
	WIRELESS_BURST,
	USB_LIST,
	USB_DOWNLOAD,
	USB_INITIALIZE,
	USB_IDENTIFY,
}
